services:
  mysql:
    image: mysql:8.4
    container_name: taskmanager-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: taskdb
      MYSQL_ROOT_PASSWORD: hashini123
      MYSQL_USER: hashini
      MYSQL_PASSWORD: hashini123
    ports:
      - "3308:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-phashini123"]
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build:
      context: ./backend/taskmanager
      dockerfile: Dockerfile
    container_name: taskmanager-backend
    restart: unless-stopped
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/taskdb
      SPRING_DATASOURCE_USERNAME: hashini
      SPRING_DATASOURCE_PASSWORD: hashini123
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./frontend/task-manager-frontend
      dockerfile: Dockerfile
    container_name: taskmanager-frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "4200:80"

volumes:
  mysql_data:
